export { default as HomePage } from './pages/homePage/HomePage'
export { default as WhoSml } from '../containers/sections/whoSml/WhoSml'
export { default as Hero } from '../containers/sections/hero/Hero'
export { default as HeroDemo } from '../containers/sections/heroDemo/HeroDemo'
export { default as FeaturedProjects } from '../containers/sections/featuredProjects/FeaturedProjects'