export { default as Hero } from './hero/Hero'
export { default as HeroDemo } from './heroDemo/HeroDemo'
export { default as Navbar } from './navbar/Navbar'
export { default as WhoSml } from './whoSml/WhoSml'
export { default as ButtonMain } from './buttonMain/ButtonMain'